image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - init: sudo apt remove composer
  - command: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" &&\
      php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" &&\
      php composer-setup.php &&\
      php -r "unlink('composer-setup.php');" &&\
      sudo cp .env.example .env &&\
      sudo ssh-keygen -q -t rsa -N '' <<< $'\ny' >/dev/null 2>&1 &&\
      sudo mysql -u root -e "create database database_name" &&\
      sudo composer install --ignore-platform-reqs;
