tasks:
 - init: sudo apt-get update -y \
      && sudo apt-get install php7.1 -y \
      && sudo apt-get install php7.1-cli php7.1-common php7.1-json php7.1-opcache php7.1-mysql php7.1-mbstring php7.1-zip php7.1-fpm php7.1-intl php7.1-simplexml -y \
      && sudo a2dismod php8.0 \
      && sudo a2enmod php7.1 \
      && sudo service apache2 restart \
      && sudo update-alternatives --set php /usr/bin/php7.1 \
      && sudo update-alternatives --set phar /usr/bin/phar7.1 \
      && sudo update-alternatives --set phar.phar /usr/bin/phar.phar7.1 \
      && sudo update-alternatives --set phpize /usr/bin/phpize7.1 \
      && sudo update-alternatives --set php-config /usr/bin/php-config7.1 \
      && sudo composer global require themosis/themosis --ignore-platform-reqs \
      && sudo mkdir dev \
      && cd dev \
      && sudo composer create-project phpmyadmin/phpmyadmin \
      && cd .. \
      && sudo mysqladmin -u root password 'gitpod';
 - command: cd dev/phpmyadmin \
      && sudo  php -S localhost:8085
image:
 file: .gitpod.Dockerfile