tasks:
 - init: sudo apt-get update -y;
 - command: sudo rm -rf ${GITPOD_REPO_ROOT}   && composer create-project themosis/themosis ${GITPOD_REPO_ROOT}   && sudo composer global require themosis/themosis --ignore-platform-reqs;
image:
 file: .gitpod.Dockerfile