image:
 file: .gitpod.Dockerfile
tasks:
 - init: sudo apt update && \
         sudo apt upgrade -y && \
         sudo apt installphp7.1 -y && \
         sudo update-alternatives --set php /usr/bin/php7.1 && \
         sudo update-alternatives --set phar /usr/bin/phar7.1 && \
         sudo update-alternatives --set phar.phar /usr/bin/phar.phar7.1 && \
         sudo update-alternatives --set phpize /usr/bin/phpize7.1 && \
         sudo update-alternatives --set php-config /usr/bin/php-config7.1 && \
         php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
         php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
         sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
         php -r "unlink('composer-setup.php');"
 - command:  composer install --ignore-platform-reqs