image:
 file: .gitpod.Dockerfile
tasks:
 - init: sudo apt update && \
         sudo apt upgrade -y && \
         sudo apt install php7.1 -y && \
         sudo update-alternatives --set php /usr/bin/php7.1 && \
         sudo update-alternatives --set phar /usr/bin/phar7.1 && \
         sudo update-alternatives --set phar.phar /usr/bin/phar.phar7.1 && \
         composer self-update --2 && \
         composer install